version: '3.8'

services:

  # Pathfinder api server
  app:
    env_file: "./.env"
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/theryangeary/pathfinder:v3 
    container_name: pathfinder-app
    environment:
      DATABASE_URL: postgresql://pathfinder:pathfinder_pass@postgres:5432/pathfinder
      SERVER_HOST: 0.0.0.0
      HTTP_PORT: 8080
      RATE_LIMIT_SESSION: 10
      RATE_LIMIT_READ: 200
      RATE_LIMIT_WRITE: 50
      RATE_LIMIT_WINDOW: 60
      COOKIE_MAX_AGE: 31536000
      REQUEST_TIMEOUT: 30
      MAX_REQUEST_SIZE: 1048576
      STRICT_REFERER: "false"
      HSTS_MAX_AGE: 31536000
      CORS_MAX_AGE: 300
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
