version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pathfinder-postgres
    environment:
      POSTGRES_DB: pathfinder
      POSTGRES_USER: pathfinder
      POSTGRES_PASSWORD: pathfinder_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pathfinder -d pathfinder"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15-alpine
    container_name: pathfinder-postgres-test
    environment:
      POSTGRES_DB: pathfinder
      POSTGRES_USER: pathfinder
      POSTGRES_PASSWORD: pathfinder_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pathfinder -d pathfinder"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Pathfinder Application (Frontend + Backend)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pathfinder:latest
    container_name: pathfinder-app
    environment:
      DATABASE_URL: postgresql://pathfinder:pathfinder_pass@postgres:5432/pathfinder
      SERVER_HOST: 0.0.0.0
      HTTP_PORT: 8080
      RUST_LOG: info
      ALLOWED_ORIGINS: http://localhost:8080
      RATE_LIMIT_SESSION: 10
      RATE_LIMIT_READ: 200
      RATE_LIMIT_WRITE: 50
      RATE_LIMIT_WINDOW: 60
      COOKIE_MAX_AGE: 31536000
      REQUEST_TIMEOUT: 30
      MAX_REQUEST_SIZE: 1048576
      STRICT_REFERER: "false"
      HSTS_MAX_AGE: 31536000
      CORS_MAX_AGE: 300
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Game Generator (for local dev, this runs as a long running container with
  # cron internal, but for fly.io deployment as a container that runs quickly
  # then exits, getting started by fly next time it is scheduled.)
  game-generator:
    build:
      context: .
    image: pathfinder:latest
    container_name: pathfinder-game-generator-cron
    command: ["game-generator", "--cron"]
    environment:
      DATABASE_URL: postgresql://pathfinder:pathfinder_pass@postgres:5432/pathfinder
      RUST_LOG: info
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
