app = "pathfinder-game"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[build]

[processes]
app = "./api-server"
cron = "./cron_entrypoint.sh"

[[services]]
processes = ["app"]
protocol = "tcp"
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
handlers = ["http"]
port = 80

[[services]]
processes = ["cron"]
protocol = "tcp"
auto_stop_machines = "off"
auto_start_machines = false
min_machines_running = 1

[[services.ports]]
handlers = ["http"]
port = 80

[env]
PORT = "8080"
RUST_LOG = "info"

[http_service]
internal_port = 8080
force_https = true
processes = ["app", "cron"]

[[http_service.checks]]
interval = "30s"
grace_period = "10s"
method = "GET"
path = "/health"
timeout = "2s"
tls_skip_verify = false

[machine]
memory = "128mb"
cpu_kind = "shared"
cpus = 1
