app = "pathfinder-game"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[build]

[processes]
app = "./api-server"
cron = "supercronic /app/crontab"

[[services]]
processes = ["app"]

[env]
PORT = "8080"
RUST_LOG = "info"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
interval = "30s"
grace_period = "10s"
method = "GET"
path = "/health"
timeout = "2s"
tls_skip_verify = false

[machine]
memory = "256mb"
cpu_kind = "shared"
cpus = 1
