name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - 'src/web/**'
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'
      - 'wrangler.toml'
      - 'vite.config.js'
      - 'tsconfig.json'
      - 'wordlist'
  workflow_dispatch:

jobs:
  test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate wordlist
        run: npm run generate-wordlist
      
      - name: Run frontend tests
        run: npm run test:run
      
      - name: Build frontend
        run: npm run build

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: test
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate wordlist
        run: npm run generate-wordlist
      
      - name: Build frontend
        run: npm run build
      
      - name: Deploy to Cloudflare Pages
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
